// Post Create
const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
const POST_CREATE_FALIED = "POST_CREATE_FALIED";
const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
// Post Show
const POST_SHOW_REQUEST = "POST_SHOW_REQUEST";
const POST_SHOW_FALIED = "POST_SHOW_FALIED";
const POST_SHOW_SUCCESS = "POST_SHOW_SUCCESS";
// Posts Index
const POSTS_INDEX_REQUEST = "POSTS_INDEX_REQUEST";
const POSTS_INDEX_FALIED = "POSTS_INDEX_FALIED";
const POSTS_INDEX_SUCCESS = "POSTS_INDEX_SUCCESS";
// Post Update
const POST_UPDATE_REQUEST = "POST_UPDATE_REQUEST";
const POST_UPDATE_FALIED = "POST_UPDATE_FALIED";
const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
// Set Current Post
const SET_POST = "SET_POST";
