const LOGIN_REQUEST = 'LOGIN_REQUEST'
const LOGIN_FAILED = 'LOGIN_FAILED'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
const LOGOUT_FAILED = 'LOGOUT_FAILED'
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

const REGISTER_REQUEST = 'REGISTER_REQUEST'
const REGISTER_FAILED = 'REGISTER_FAILED'
const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'
